/* ==========================================================================
   قاعدة بيانات الأصناف المركزية لأسواق البركة (Al-Barakah Products Catalog)
   ========================================================================== */
const BARAKAH_PRODUCTS = [
  // --- الألبان والأجبان (DAIRY) ---
  {
    id: 101,
    barcode: "6221007001015",
    sku: "DAI-JUH-1L",
    dept: "DAIRY",
    nameAr: "حليب جهينة كامل الدسم مبستر 1 لتر",
    nameEn: "Juhayna Pure Full Cream Milk 1L",
    brand: "جهينة",
    price: 44.50,
    cost: 37.00,
    stock: 85,
    unit: "عبوة 1 لتر",
    icon: "🥛",
    badge: "الأكثر مبيعاً"
  },
  {
    id: 102,
    barcode: "6221008003030",
    sku: "DAI-DOM-500",
    dept: "DAIRY",
    nameAr: "جبنة دومتي بلس فيتا 500 جم",
    nameEn: "Domty Plus Feta Cheese 500g",
    brand: "دومتي",
    price: 38.00,
    cost: 31.00,
    stock: 60,
    unit: "علبة 500 جم",
    icon: "🧀",
    badge: null
  },
  {
    id: 103,
    barcode: "6222005001122",
    sku: "DAI-MAR-6PK",
    dept: "DAIRY",
    nameAr: "زبادي المراعي طبيعي 105 جم (عرض 6 علب)",
    nameEn: "Almarai Fresh Plain Yoghurt (6-Pack)",
    brand: "المراعي",
    price: 42.00,
    cost: 34.00,
    stock: 45,
    unit: "مجموعة 6 علب",
    icon: "🥣",
    badge: "وفر 6 ج.م"
  },
  {
    id: 104,
    barcode: "6229000101010",
    sku: "DAI-EGG-30",
    dept: "DAIRY",
    nameAr: "كرتونة بيض أحمر مزارع البركة طازج (30 بيضة)",
    nameEn: "Fresh Farm Red Eggs (30-Pack Tray)",
    brand: "مزارع البركة",
    price: 168.00,
    cost: 150.00,
    stock: 35,
    unit: "كرتونة 30 حبة",
    icon: "🥚",
    badge: "طازج يومياً"
  },

  // --- المؤن والزيوت والبقوليات (PANTRY) ---
  {
    id: 201,
    barcode: "6223000551020",
    sku: "PAN-DOH-1KG",
    dept: "PANTRY",
    nameAr: "أرز مصري عريض الحبة فاخر الضحى 1 كجم",
    nameEn: "El Doha Premium Egyptian Rice 1kg",
    brand: "الضحى",
    price: 39.50,
    cost: 33.00,
    stock: 140,
    unit: "كيس 1 كجم",
    icon: "🍚",
    badge: null
  },
  {
    id: 202,
    barcode: "6221155008901",
    sku: "PAN-CRY-16L",
    dept: "PANTRY",
    nameAr: "زيت ذرة كريستال نقي 1.6 لتر",
    nameEn: "Crystal Pure Corn Cooking Oil 1.6L",
    brand: "كريستال",
    price: 128.00,
    cost: 112.00,
    stock: 55,
    unit: "زجاجة 1.6 لتر",
    icon: "🌻",
    badge: "خصم خاص"
  },
  {
    id: 203,
    barcode: "6221200003021",
    sku: "PAN-REG-400",
    dept: "PANTRY",
    nameAr: "مكرونة ريجينا قلم سيمولينا قمح صلب 400 جم",
    nameEn: "Regina Penne Rigate Durum Pasta 400g",
    brand: "ريجينا",
    price: 21.00,
    cost: 16.50,
    stock: 90,
    unit: "كيس 400 جم",
    icon: "🍝",
    badge: null
  },
  {
    id: 204,
    barcode: "6221004008812",
    sku: "PAN-OSR-1KG",
    dept: "PANTRY",
    nameAr: "سكر أبيض نقي فاخر الأسرة 1 كجم",
    nameEn: "El Osra Pure White Sugar 1kg",
    brand: "الأسرة",
    price: 36.00,
    cost: 30.00,
    stock: 110,
    unit: "كيس 1 كجم",
    icon: "🍬",
    badge: null
  },

  // --- اللحوم والدواجن (MEAT) ---
  {
    id: 301,
    barcode: "6229000123456",
    sku: "MEA-BEEF-1KG",
    dept: "MEAT",
    nameAr: "مكعبات لحم بقري بلدي أحمر طازج 1 كجم",
    nameEn: "Fresh Egyptian Baladi Beef Cubes 1kg",
    brand: "جزارة البركة",
    price: 440.00,
    cost: 390.00,
    stock: 18,
    unit: "كيلوجرام",
    icon: "🥩",
    badge: "ذبح اليوم"
  },
  {
    id: 302,
    barcode: "6229000123470",
    sku: "MEA-CHX-1KG",
    dept: "MEAT",
    nameAr: "صدور دجاج بانيه متبلة طازجة 1 كجم",
    nameEn: "Fresh Boneless Chicken Breast Fillet 1kg",
    brand: "مزارع البركة",
    price: 245.00,
    cost: 215.00,
    stock: 25,
    unit: "طبق 1 كجم",
    icon: "🍗",
    badge: null
  },

  // --- المشروبات والمنبهات (BEVERAGES) ---
  {
    id: 401,
    barcode: "6224000112233",
    sku: "BEV-ARO-250",
    dept: "BEVERAGES",
    nameAr: "شاي أسود كيني ناعم العروسة 250 جم",
    nameEn: "El Arosa Fine Dust Black Tea 250g",
    brand: "العروسة",
    price: 52.50,
    cost: 46.00,
    stock: 95,
    unit: "عبوة 250 جم",
    icon: "☕",
    badge: null
  },
  {
    id: 402,
    barcode: "6221100012023",
    sku: "BEV-ABD-100",
    dept: "BEVERAGES",
    nameAr: "بن تركي محوج عبد المعبود فاتح 100 جم",
    nameEn: "Abdel Maboud Cardamom Turkish Coffee 100g",
    brand: "عبد المعبود",
    price: 49.00,
    cost: 41.00,
    stock: 50,
    unit: "كيس 100 جم",
    icon: "🫘",
    badge: null
  },

  // --- المنظفات والعناية (CLEANING) ---
  {
    id: 501,
    barcode: "6221002005012",
    sku: "CLN-ARI-4KG",
    dept: "CLEANING",
    nameAr: "مسحوق أوتوماتيك أريال لافندر 4 كجم",
    nameEn: "Ariel Automatic Laundry Powder 4kg",
    brand: "أريال",
    price: 285.00,
    cost: 250.00,
    stock: 22,
    unit: "كيس 4 كجم",
    icon: "🧺",
    badge: "توفير عائلي"
  },
  {
    id: 502,
    barcode: "6221003004040",
    sku: "CLN-PRI-1L",
    dept: "CLEANING",
    nameAr: "سائل غسيل الأطباق المركز بريل ليمون 1 لتر",
    nameEn: "Pril Power Degreaser Lemon Liquid 1L",
    brand: "بريل",
    price: 48.00,
    cost: 39.00,
    stock: 40,
    unit: "زجاجة 1 لتر",
    icon: "🍋",
    badge: null
  }
];
